FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r app/requirements.txt

ENV MODEL_PATH=/app/data/model.joblib

EXPOSE 8080
CMD ["uvicorn", "app.predictor_app:app", "--host", "0.0.0.0", "--port", "8080"]
